### ISSUE TITLE
Error when running tests with Solr 4.3.1

### ISSUE THREAD

**Issue by anti-social** [toastdriven/pysolr#90]
``` bash
$ nosetests tests                                      
..........................E...........
======================================================================
ERROR: test_extract (tests.SolrTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexk/projects/pysolr/tests/client.py", line 425, in test_extract
    extracted = self.solr.extract(fake_f)
  File "/home/alexk/projects/pysolr/pysolr.py", line 871, in extract
    files={'file': (file_obj.name, file_obj)})
  File "/home/alexk/projects/pysolr/pysolr.py", line 296, in _send_request
    raise SolrError(error_message)
SolrError: [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">10</int></lst><lst name="error"><str name="msg">Document is missing mandatory uniqueKey field: id</str><int name="code">400</int></ls$
></response>
```

**Comment by galuszkak** [comment]
This issue should be closed as I believe it was fixed in #104 ;).
